"""add unique constraint to habit completions

Revision ID: f12dfb5f1954
Revises: 
Create Date: 2026-05-12 21:46:24.714014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f12dfb5f1954'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_habit_completion_per_day', 'habit_completions', ['habit_id', 'completed_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_habit_completion_per_day', 'habit_completions', type_='unique')
    # ### end Alembic commands ###
